from pydantic import BaseModel, Field
from typing import Literal


class EscalationStructuredOutput(BaseModel):
    critical_query: bool = Field(  # fixed typo: critical_quey -> critical_query
        ...,
        description="True if the priority of the query is critical, else False"
    )
    ticket_id: str = Field(
        ...,
        description="The support ticket ID generated by the create_support_ticket tool"
    )
    priority: Literal["Low", "Medium", "High", "Critical"] = Field(
        ...,
        description="The severity level assigned to this complaint"
    )
    sentiment: Literal["neutral", "frustrated", "angry"] = Field(
        ...,
        description="The detected sentiment of the customer's message"
    )
    human_handoff: bool = Field(
        ...,
        description="True if this case must be routed to a human agent instead of being handled by the bot"
    )
    suggestion: str = Field(
        default="",
        description="A helpful suggestion for the customer; empty string if human_handoff is True"
    )